language: python

sudo: false

services:
  - mongodb

env:
  - MONGO=127.0.0.1:27017

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .

# command to run tests
script: py.test -v
